name=XENSIV PAS Gas Sensors
version=0.1.0
author=Infineon Technologies
maintainer=Infineon Technologies <www.infineon.com>
sentence="Arduino library for Infineon's XENSIV™ PAS gas sensors."
paragraph="This library provides a simple interface to interact with Infineon's XENSIV™ PAS gas sensors, including CO2 and refrigerant gas sensors."
category=Sensors
url=https://github.com/Infineon/arduino-xensiv-pas-gas-sensor
architectures=*
includes=xensiv_pas_gas_ino.hpp