options:
  # USE_CORE:
  #   name: local
  #   url: https://blabla
  #   name: Infineon:xmc:3.5.4
  #   url: https://github.com/Infineon/XMC-for-Arduino/releases/download/3.5.4/package_infineon_index.json
  SEND_JOB_START_TOKEN: false
  # PARSER_END_TOKEN: loop done.

unit-test:
    unit-test-a2l-psoc:
      - description: Compiling, flashing and monitoring of test-a2l-psoc-board
        command: make test_xensiv_pas_gas_a2l
        query: a2l_iic_psoc_board == '1:1'
        working_dir: tests/
    
    unit-test-r290-psoc:
      - description: Compiling, flashing and monitoring of test-r290-co2-psoc-board
        command: make test_xensiv_pas_gas_r290
        query: r290_iic_psoc_board == '1:1'
        working_dir: tests/

    unit-test-co2-psoc:
      - description: Compiling, flashing and monitoring of test-co2-psoc-board
        command: make test_xensiv_pas_gas
        query: co2_iic_psoc_board == '1:1'
        working_dir: tests/